# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d4b39fabbdad76fbd4ee5813b2dc7eb37690035d61dafa870af0990d4c271aad92577aae04649c1f1aeb6ab0fc3e16117855d63009be08a0e813175c5960dee9

test:
  secret_key_base: 51827e9db7e48ee7399c69302e0890021415f5fc5bbdd652f0b2d25e70eed3c4cd69acf8978ecda99ffbf951d7e4ff2ec7647a0929af62c7f8f3ec33c0ba4d51

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
